# GitHub Sponsors configuration
# Uncomment and fill in your sponsorship information

# github: [declue]
# ko_fi: # Replace with a single Ko-fi username
# open_collective: # Replace with a single Open Collective username
# patreon: # Replace with a single Patreon username
# custom: # Replace with up to 4 custom sponsorship URLs
