# Auto-labeling configuration for PRs (v6 format)

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

# UI/Frontend
ui:
  - changed-files:
    - any-glob-to-any-file: ['components/**/*', 'app/**/*', '**/*.tsx', 'public/**/*']

# Backend/Electron
electron:
  - changed-files:
    - any-glob-to-any-file: ['electron/**/*', 'electron-builder.json']

# LangGraph
langgraph:
  - changed-files:
    - any-glob-to-any-file: ['lib/langgraph/**/*']

# RAG System
rag:
  - changed-files:
    - any-glob-to-any-file:
      - 'lib/documents/**/*'
      - 'electron/services/vectordb.ts'
      - 'electron/ipc/handlers/vectordb.ts'
      - 'electron/ipc/handlers/embeddings.ts'
      - 'components/rag/**/*'

# MCP Integration
mcp:
  - changed-files:
    - any-glob-to-any-file:
      - 'lib/mcp/**/*'
      - 'electron/ipc/handlers/mcp.ts'
      - 'components/mcp/**/*'

# LLM
llm:
  - changed-files:
    - any-glob-to-any-file:
      - 'lib/llm/**/*'
      - 'electron/ipc/handlers/llm.ts'

# Configuration
config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
      - '.env*'
      - 'lib/config/**/*'
      - 'electron/ipc/handlers/config.ts'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'

# Testing
testing:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'

# CI/CD
ci-cd:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

# Security
security:
  - changed-files:
    - any-glob-to-any-file:
      - 'SECURITY.md'
      - '.github/SECURITY*.md'
      - 'lib/config/encryption.ts'
      - 'electron/services/token-manager.ts'
      - '.github/workflows/security*.yml'

# GitHub Integration
github:
  - changed-files:
    - any-glob-to-any-file:
      - 'electron/ipc/handlers/github.ts'
      - 'lib/auth/github-oauth.ts'
      - 'components/settings/GitHubOAuthSettings.tsx'
