#!/bin/bash
echo "=== Extension System Verification Report ==="
echo ""
echo "1. Extension File Count:"
echo "   - Editor Extension: $(find extensions/editor -type f | wc -l) files"
echo "   - Browser Extension: $(find extensions/browser -type f | wc -l) files"
echo "   - Presentation Extension: $(find extensions/presentation -type f | wc -l) files"
echo "   - TOTAL: $(find extensions -type f | wc -l) files"
echo ""
echo "2. Extension Components:"
echo "   - Editor Components: $(ls extensions/editor/components/*.tsx 2>/dev/null | wc -l) files"
echo "   - Browser Components: $(ls extensions/browser/components/*.tsx 2>/dev/null | wc -l) files"
echo ""
echo "3. Extension Agents:"
echo "   - Editor Agents: $(ls extensions/editor/agents/*.ts 2>/dev/null | wc -l) files"
echo "   - Browser Agents: $(ls extensions/browser/agents/*.ts 2>/dev/null | wc -l) files"
echo ""
echo "4. Extension Tools:"
echo "   - Editor Tools: $(ls extensions/editor/tools/*.ts 2>/dev/null | wc -l) files"
echo ""
echo "5. Extension Locales:"
echo "   - Editor Locales: $(ls extensions/editor/locales/*.json 2>/dev/null | wc -l) files"
echo "   - Browser Locales: $(ls extensions/browser/locales/*.json 2>/dev/null | wc -l) files"
echo "   - Presentation Locales: $(ls extensions/presentation/locales/*.json 2>/dev/null | wc -l) files"
echo ""
echo "6. Extension Types:"
echo "   - Editor Types: $(find extensions/editor/types -name "*.ts" 2>/dev/null | wc -l) files"
echo "   - Browser Types: $(find extensions/browser/types -name "*.ts" 2>/dev/null | wc -l) files"
echo ""
echo "7. Main App Cleanup:"
echo "   - Old components/editor deleted: $(ls components/editor/*.tsx 2>/dev/null | wc -l) remaining"
echo "   - Old components/browser deleted: $(ls components/browser/*.tsx 2>/dev/null | wc -l) remaining"
echo "   - Old lib/langgraph/tools deleted: $(ls lib/langgraph/tools/*.ts 2>/dev/null | wc -l) remaining"
echo ""
