name: Question
description: Ask a question about SEPilot Desktop
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check the documentation first.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - LangGraph Integration
        - RAG System
        - MCP Servers
        - LLM Providers
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Please describe your question in detail
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you've tried, documentation you've read, etc.)
      placeholder: Any additional context that might help us answer your question
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
        - Not applicable
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of SEPilot Desktop are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
